---
# PostgreSQL for Feast Feature Store (OpenShift-Compatible)
# Uses Red Hat Universal Base Image (UBI) PostgreSQL
# 
# ARCHITECTURE:
# - 3 Databases: feast_registry, feast_offline, feast_online
# - User: feast / feast_password (change in production)
# - Storage: 50Gi PVC for feature data
# - Resources: 4Gi RAM, 2 CPU (tuned for Ray workloads)

apiVersion: v1
kind: Secret
metadata:
  name: feast-postgres-secret
  namespace: kft-feast-quickstart
type: Opaque
stringData:
  # Primary database (will be created automatically)
  POSTGRESQL_DATABASE: feast_registry
  POSTGRESQL_USER: feast
  POSTGRESQL_PASSWORD: feast_password  # CHANGE IN PRODUCTION!
  
  # Connection strings for applications
  FEAST_REGISTRY_URI: postgresql+psycopg://feast:feast_password@feast-postgres.kft-feast-quickstart.svc.cluster.local:5432/feast_registry
  FEAST_OFFLINE_URI: postgresql+psycopg://feast:feast_password@feast-postgres.kft-feast-quickstart.svc.cluster.local:5432/feast_offline
  FEAST_ONLINE_URI: postgresql+psycopg://feast:feast_password@feast-postgres.kft-feast-quickstart.svc.cluster.local:5432/feast_online
  
---
apiVersion: v1
kind: Service
metadata:
  name: feast-postgres
  namespace: kft-feast-quickstart
  labels:
    app: feast-postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
  selector:
    app: feast-postgres
  clusterIP: None
  
---
# ConfigMap with initialization script
apiVersion: v1
kind: ConfigMap
metadata:
  name: feast-postgres-init
  namespace: kft-feast-quickstart
data:
  init-databases.sh: |
    #!/bin/bash
    set -e
    
    echo "================================================"
    echo "Initializing Feast PostgreSQL Databases"
    echo "================================================"
    
    # Wait for PostgreSQL to be ready
    until pg_isready -U ${POSTGRESQL_USER} -d ${POSTGRESQL_DATABASE}; do
      echo "Waiting for PostgreSQL to be ready..."
      sleep 2
    done
    
    echo "✓ PostgreSQL is ready"
    
    # Create additional databases for Feast
    psql -v ON_ERROR_STOP=1 --username "${POSTGRESQL_USER}" --dbname "${POSTGRESQL_DATABASE}" <<-EOSQL
      -- Create feast_offline database
      SELECT 'CREATE DATABASE feast_offline'
      WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'feast_offline')\gexec
      
      -- Create feast_online database
      SELECT 'CREATE DATABASE feast_online'
      WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'feast_online')\gexec
      
      -- Grant permissions
      GRANT ALL PRIVILEGES ON DATABASE feast_offline TO ${POSTGRESQL_USER};
      GRANT ALL PRIVILEGES ON DATABASE feast_online TO ${POSTGRESQL_USER};
    EOSQL
    
    echo "✓ Created databases: feast_offline, feast_online"
    
    # Initialize feast_offline schema
    psql -v ON_ERROR_STOP=1 --username "${POSTGRESQL_USER}" --dbname "feast_offline" <<-EOSQL
      -- Grant schema permissions
      GRANT ALL PRIVILEGES ON SCHEMA public TO ${POSTGRESQL_USER};
      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${POSTGRESQL_USER};
      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${POSTGRESQL_USER};
      
      -- Create sales_features table
      CREATE TABLE IF NOT EXISTS sales_features (
        store INTEGER NOT NULL,
        dept INTEGER NOT NULL,
        date TIMESTAMP NOT NULL,
        weekly_sales DOUBLE PRECISION NOT NULL,
        is_holiday INTEGER NOT NULL,
        week_of_year INTEGER,
        month INTEGER,
        quarter INTEGER,
        sales_lag_1 DOUBLE PRECISION,
        sales_lag_2 DOUBLE PRECISION,
        sales_lag_4 DOUBLE PRECISION,
        sales_rolling_mean_4 DOUBLE PRECISION,
        sales_rolling_mean_12 DOUBLE PRECISION,
        sales_rolling_std_4 DOUBLE PRECISION,
        PRIMARY KEY (store, dept, date)
      );
      
      -- Create indexes for sales_features
      CREATE INDEX IF NOT EXISTS idx_sales_date ON sales_features(date);
      CREATE INDEX IF NOT EXISTS idx_sales_store_dept ON sales_features(store, dept);
      
      -- Create store_features table
      CREATE TABLE IF NOT EXISTS store_features (
        store INTEGER NOT NULL,
        dept INTEGER NOT NULL,
        date TIMESTAMP NOT NULL,
        temperature DOUBLE PRECISION,
        fuel_price DOUBLE PRECISION,
        cpi DOUBLE PRECISION,
        unemployment DOUBLE PRECISION,
        markdown1 DOUBLE PRECISION,
        markdown2 DOUBLE PRECISION,
        markdown3 DOUBLE PRECISION,
        markdown4 DOUBLE PRECISION,
        markdown5 DOUBLE PRECISION,
        total_markdown DOUBLE PRECISION,
        has_markdown INTEGER,
        store_type VARCHAR(10),
        store_size INTEGER,
        PRIMARY KEY (store, dept, date)
      );
      
      -- Create indexes for store_features
      CREATE INDEX IF NOT EXISTS idx_store_date ON store_features(date);
      CREATE INDEX IF NOT EXISTS idx_store_store_dept ON store_features(store, dept);
    EOSQL
    
    echo "✓ Initialized feast_offline schema"
    
    # Initialize feast_online schema
    psql -v ON_ERROR_STOP=1 --username "${POSTGRESQL_USER}" --dbname "feast_online" <<-EOSQL
      -- Grant schema permissions
      GRANT ALL PRIVILEGES ON SCHEMA public TO ${POSTGRESQL_USER};
      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${POSTGRESQL_USER};
      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${POSTGRESQL_USER};
    EOSQL
    
    echo "✓ Initialized feast_online schema"
    
    # Create completion marker
    touch /var/lib/pgsql/data/.feast_init_complete
    
    echo "================================================"
    echo "Feast PostgreSQL Initialization Complete!"
    echo "================================================"
    echo "Databases:"
    echo "  ✓ feast_registry (metadata)"
    echo "  ✓ feast_offline (feature storage)"
    echo "  ✓ feast_online (serving)"
    echo ""
    echo "Tables in feast_offline:"
    echo "  ✓ sales_features (with indexes)"
    echo "  ✓ store_features (with indexes)"
    echo "================================================"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: feast-postgres
  namespace: kft-feast-quickstart
spec:
  serviceName: feast-postgres
  replicas: 1
  selector:
    matchLabels:
      app: feast-postgres
  template:
    metadata:
      labels:
        app: feast-postgres
    spec:
      # Init container to run database initialization
      initContainers:
      - name: init-databases
        image: registry.redhat.io/rhel9/postgresql-15:latest
        command:
        - /bin/bash
        - -c
        - |
          # Check if already initialized
          if [ -f /var/lib/pgsql/data/.feast_init_complete ]; then
            echo "Databases already initialized, skipping..."
            exit 0
          fi
          
          # Wait for main container to start PostgreSQL
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h localhost -U ${POSTGRESQL_USER}; do
            sleep 2
          done
          
          # Run initialization script
          /scripts/init-databases.sh
        envFrom:
        - secretRef:
            name: feast-postgres-secret
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/pgsql/data
        - name: init-scripts
          mountPath: /scripts
      
      containers:
      - name: postgresql
        image: registry.redhat.io/rhel9/postgresql-15:latest
        ports:
        - containerPort: 5432
          name: postgresql
        env:
        # Tuning for Ray workloads (parallel queries)
        - name: POSTGRESQL_MAX_CONNECTIONS
          value: "200"
        - name: POSTGRESQL_SHARED_BUFFERS
          value: "1GB"
        - name: POSTGRESQL_EFFECTIVE_CACHE_SIZE
          value: "3GB"
        - name: POSTGRESQL_WORK_MEM
          value: "16MB"
        - name: POSTGRESQL_MAINTENANCE_WORK_MEM
          value: "256MB"
        envFrom:
        - secretRef:
            name: feast-postgres-secret
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/pgsql/data
        - name: init-scripts
          mountPath: /scripts
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          exec:
            command:
            - /usr/libexec/check-container
            - --live
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - /usr/libexec/check-container
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
      volumes:
      - name: init-scripts
        configMap:
          name: feast-postgres-init
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi  # Increased for feature data (421K rows + indexes)

